export const GET_LOG_IN_REQUEST = 'GET_LOG_IN_REQUEST';
export const GET_LOG_IN_FAILURE = 'GET_LOG_IN_FAILURE';
export const GET_LOG_IN_SUCCESS = 'GET_LOG_IN_SUCCESS';
export const GET_LOG_OUT = 'GET_LOG_OUT';

export const GET_USERS_FETCH_REQUEST = 'GET_USERS_FETCH_REQUEST';
export const GET_USERS_FETCH_FAILURE = 'GET_USERS_FETCH_FAILURE';
export const GET_USERS_FETCH_SUCCESS = 'GET_USERS_FETCH_SUCCESS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const GET_SELECTED_USER = 'GET_SELECTED_USER';


export const GET_PROFILE_EDITED_REQUEST = 'GET_PROFILE_EDITED_REQUEST';
export const GET_PROFILE_EDITED_FAILURE = 'GET_PROFILE_EDITED_FAILURE';
export const GET_PROFILE_EDITED_SUCCESS = 'GET_PROFILE_EDITED_SUCCESS';