export const GET_LOG_IN_REQUEST = 'GET_LOG_IN_REQUEST';
export const GET_LOG_IN_FAILURE = 'GET_LOG_IN_FAILURE';
export const GET_LOG_IN_SUCCESS = 'GET_LOG_IN_SUCCESS';
export const GET_LOG_OUT = 'GET_LOG_OUT';

export const GET_USERS_FETCH_REQUEST = 'GET_USERS_FETCH_REQUEST';
export const GET_USERS_FETCH_FAILURE = 'GET_USERS_FETCH_FAILURE';
export const GET_USERS_FETCH_SUCCESS = 'GET_USERS_FETCH_SUCCESS';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const FOLLOW = 'FOLLOW';
export const UNFOLLOW = 'UNFOLLOW';


export const GET_PROFILE_EDITED_REQUES = 'GET_PROFILE_EDITED_REQUES';
export const GET_PROFILE_EDITED_FAILURE = 'GET_PROFILE_EDITED_FAILURE';
export const GET_PROFILE_EDITED_SUCCESS = 'GET_PROFILE_EDITED_SUCCESS';
export const GET_PROFILE_STATUS_EDITED = 'GET_PROFILE_STATUS__EDITED';
export const GET_PROFILE_STATUS_CHANGED = 'GET_PROFILE_STATUS__CHANGED';
export const ADD_NEW_POST = 'ADD_NEW_POST';
export const DELETE_MY_POST = 'DELETE_MY_POST';

export const GET_PHOTO_FETCH_REQUEST = 'GET_PHOTO_FETCH_REQUEST';
export const GET_PHOTO_FETCH_FAILURE = 'GET_PHOTO_FETCH_FAILURE';
export const GET_PHOTO_FETCH_SUCCESS = 'GET_PHOTO_FETCH_SUCCESS';

export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';

export const GET_FRIENDS_FETCH_REQUEST = 'GET_FRIENDS_FETCH_REQUEST';
export const GET_FRIENDS_FETCH_FAILURE = 'GET_FRIENDS_FETCH_FAILURE';
export const GET_FRIENDS_FETCH_SUCCESS = 'GET_FRIENDS_FETCH_SUCCESS';
export const FOLLOW_FRIENDS = 'FOLLOW_FRIENDS';
export const UNFOLLOW_FRIENDS = 'UNFOLLOW_FRIENDS';